BobsShirtEmporium/BobsShirtEmporium/Controllers/ShirtsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BobsShirtEmporium.Data;
using BobsShirtEmporium.Models;

namespace BobsShirtEmporium.Controllers
{
    public class ShirtsController : Controller
    {
        private readonly ShirtDbContext _context;

        public ShirtsController(ShirtDbContext context)
        {
            _context = context;
        }

        // GET: Shirts
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Shirts.ToListAsync());
        //}

        // GET: Shirts search by title
        public async Task<IActionResult> Index(string searchString, string styleString, string colorString)
        {
            IQueryable<string> styleQuery = from m in _context.Shirts
                                            orderby m.Style
                                            select m.Style;

            IQueryable<string> colorQuery = from m in _context.Shirts
                                            orderby m.Color
                                            select m.Color;

            var shirts = from m in _context.Shirts
                         select m;

            if(!String.IsNullOrEmpty(searchString))
            {
                shirts = shirts.Where(s => s.Title.Contains(searchString) || s.Description.Contains(searchString));
            }

            if(!String.IsNullOrEmpty(styleString))
            {
                shirts = shirts.Where(s => s.Style == styleString);
            }

            if(!String.IsNullOrEmpty(colorString))
            {
                shirts = shirts.Where(s => s.Color == colorString);
            }

            var shirtSearchVM = new ShirtsSearchViewModel
            {
                Styles = new SelectList(await styleQuery.Distinct().ToListAsync()),
                Colors = new SelectList(await colorQuery.Distinct().ToListAsync()),
                Shirts = await shirts.ToListAsync()
            };

            return View(shirtSearchVM);
        }

        // GET: Shirts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shirt = await _context.Shirts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shirt == null)
            {
                return NotFound();
            }

            return View(shirt);
        }

        // GET: Shirts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shirts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Size,Color,Style,Price,Stock")] Shirt shirt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shirt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shirt);
        }

        // GET: Shirts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shirt = await _context.Shirts.FindAsync(id);
            if (shirt == null)
            {
                return NotFound();
            }
            return View(shirt);
        }

        // POST: Shirts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Size,Color,Style,Price,Stock,ImagePath")] Shirt shirt)
        {
            if (id != shirt.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shirt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShirtExists(shirt.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shirt);
        }

        // GET: Shirts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shirt = await _context.Shirts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shirt == null)
            {
                return NotFound();
            }

            return View(shirt);
        }

        // POST: Shirts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shirt = await _context.Shirts.FindAsync(id);
            _context.Shirts.Remove(shirt);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShirtExists(int id)
        {
            return _context.Shirts.Any(e => e.Id == id);
        }
    }
}

BobsShirtEmporium/BobsShirtEmporium/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bob's Shirt Emporium</title>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/25baf12524.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar bg-primary navbar-light navbar-expand-sm">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-store-alt"></i> BSE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shirts" asp-action="Index"><i class="fas fa-tshirt"></i> Our Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About"><i class="fas fa-info-circle"></i> About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Careers"><i class="fas fa-briefcase"></i></i> Careers</a>
                        </li>
                    </ul>
                </div>
                <form asp-controller="Shirts" asp-action="Index" method="get" class="form-inline">
                    <input class="form-control mr-sm-2" type="text" name="searchString" />
                    <button class="btn btn-primary my-2 my-sm-0 text-dark" type="submit">
                        <i class="fas fa-search"></i> Search
                    </button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2021 - Bob's Shirt Emporium | Online Storefront</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>